#pragma once

// #define ORYX_CONFIGURATOR
// TESTING

// #define TAP_CODE_DELAY 62
// #define MOONLANDER_I2C_TIMEOUT 10
/*#define IS31FL3731_I2C_TIMEOUT 10*/
/*#define RGB_MATRIX_LED_PROCESS_LIMIT 5*/
/*#define RGB_MATRIX_LED_FLUSH_LIMIT 26*/

#define SERIAL_NUMBER "JqnWm/yoZDXd"
#define USB_SUSPEND_WAKEUP_DELAY 0

// #define FIRMWARE_VERSION u8"oLAqG/DyvEJ"
// #define RAW_USAGE_PAGE 0xFF60
// #define RAW_USAGE_ID 0x61
#define LAYER_STATE_8BIT
#define RGB_MATRIX_STARTUP_SPD 60

#define MOONLANDER_USER_LEDS

#define FORCE_NKRO
#undef USB_POLLING_INTERVAL_MS
#define USB_POLLING_INTERVAL_MS 1
//
// #undef QMK_KEYS_PER_SCAN
// #define QMK_KEYS_PER_SCAN 4

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#undef TAPPING_TERM
#define TAPPING_TERM 175


#define ONESHOT_TIMEOUT 2000

#define IDLE_PROFILE_INDEX 1

#define RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_KEYREACTIVE_ENABLED
#undef RGB_DISABLE_WHEN_USB_SUSPENDED
#define RGB_DISABLE_WHEN_USB_SUSPENDED true
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS

#define ENABLE_RGB_MATRIX_UNDERGLOW_WAVE
#define ENABLE_RGB_MATRIX_CHATGPT

// #define IGNORE_MOD_TAP_INTERRUPT_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define PERMISSIVE_HOLD
#define TAPPING_TERM_PER_KEY
// #define QUICK_TAP_TERM 130
#define QUICK_TAP_PER_KEY
#define FLOW_TAP_TERM 0

// COMBO SECTION
#define COMBO_VARIABLE_LEN
#define COMBO_TERM 50
#define COMBO_SHOULD_TRIGGER
#define COMBO_STRICT_TIMER
#define COMBO_TERM_PER_COMBO

// #define ACHORDION_STREAK
#define CHORDAL_HOLD

// REPEAT AND MAGIC
/*#define NO_ALT_REPEAT_KEY*/

#define JOYSTICK_BUTTON_COUNT 4
#define JOYSTICK_AXES_COUNT 0
#define JOYSTICK_AXES_RESOLUTION 8

#undef ENABLE_RGB_MATRIX_ALPHAS_MODS
#undef ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#undef ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#undef ENABLE_RGB_MATRIX_BREATHING
#undef ENABLE_RGB_MATRIX_BAND_SAT
#undef ENABLE_RGB_MATRIX_BAND_VAL
#undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#undef ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#undef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#undef ENABLE_RGB_MATRIX_CYCLE_ALL
#undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#undef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#undef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#undef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#undef ENABLE_RGB_MATRIX_FLOWER_BLOOMING
#undef ENABLE_RGB_MATRIX_RAINDROPS
#undef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#undef ENABLE_RGB_MATRIX_HUE_BREATHING
#undef ENABLE_RGB_MATRIX_HUE_PENDULUM
#undef ENABLE_RGB_MATRIX_HUE_WAVE
#undef ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#undef ENABLE_RGB_MATRIX_PIXEL_FLOW
#undef ENABLE_RGB_MATRIX_PIXEL_RAIN
#undef ENABLE_RGB_MATRIX_TYPING_HEATMAP
#undef ENABLE_RGB_MATRIX_DIGITAL_RAIN
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#undef ENABLE_RGB_MATRIX_SPLASH
#undef ENABLE_RGB_MATRIX_MULTISPLASH
#undef ENABLE_RGB_MATRIX_SOLID_SPLASH
#undef ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
#undef ENABLE_RGB_MATRIX_STARLIGHT
#undef ENABLE_RGB_MATRIX_STARLIGHT_DUAL_HUE
#undef ENABLE_RGB_MATRIX_STARLIGHT_DUAL_SAT
#undef ENABLE_RGB_MATRIX_RIVERFLOW
