#pragma once

// #define ORYX_CONFIGURATOR
// TESTING

#define TAP_CODE_DELAY 25
// #define MOONLANDER_I2C_TIMEOUT 10
// #define IS31FL3731_I2C_TIMEOUT 10
// #define RGB_MATRIX_LED_PROCESS_LIMIT 5
// #define RGB_MATRIX_LED_FLUSH_LIMIT 26

#define USB_SUSPEND_WAKEUP_DELAY 0

#define FIRMWARE_VERSION u8"oLAqG/DyvEJ"
// #define RAW_USAGE_PAGE 0xFF60
// #define RAW_USAGE_ID 0x61
#define LAYER_STATE_8BIT
#define RGB_MATRIX_STARTUP_SPD 60

#define MOONLANDER_USER_LEDS

#define FORCE_NKRO
// #undef USB_POLLING_INTERVAL_MS
// #define USB_POLLING_INTERVAL_MS 1
//
// #undef QMK_KEYS_PER_SCAN
// #define QMK_KEYS_PER_SCAN 12

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#undef TAPPING_TERM
#define TAPPING_TERM 175


#define ONESHOT_TIMEOUT 2000

#define IDLE_PROFILE_INDEX 1

#define RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_KEYREACTIVE_ENABLED
#undef RGB_DISABLE_WHEN_USB_SUSPENDED
#define RGB_DISABLE_WHEN_USB_SUSPENDED true
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS

#define ENABLE_RGB_MATRIX_UNDERGLOW_WAVE
#define ENABLE_RGB_MATRIX_CHATGPT

// #define IGNORE_MOD_TAP_INTERRUPT_PER_KEY
// #define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define PERMISSIVE_HOLD
#define TAPPING_TERM_PER_KEY
// #define QUICK_TAP_TERM 130
#define QUICK_TAP_PER_KEY

// COMBO SECTION
#define COMBO_VARIABLE_LEN
#define COMBO_TERM 50
#define COMBO_SHOULD_TRIGGER
#define COMBO_STRICT_TIMER
#define COMBO_TERM_PER_COMBO

#define ACHORDION_STREAK

// REPEAT AND MAGIC
#define NO_ALT_REPEAT_KEY
